FROM {{ baseImage }}

# Set working directory to {{ imageWorkDir }}
WORKDIR {{ imageWorkDir }}

# Copy requirements file and install them with pip
COPY {{ dependencyFile }} {{ imageWorkDir }}
RUN pip install -r {{ dependencyFile }}

# Set exposed ports
{% for portDef in ports -%}
EXPOSE {{ portDef.port }}{% if portDef.protocol %}/{{ portDef.protocol }}{% endif %}
{% endfor %}
USER {{ userID }}

# Copy all files to {{ imageWorkDir }}
COPY {{ codeDir }} {{ imageWorkDir }}

# Default command is in JSON syntax and runs gunicorn directly
CMD ["gunicorn", "-b", "0.0.0.0:{{ appPort }}", "-w", "4", "{{ mainFile|trim('.py') }}:{{ appObject }}"]
