FROM python:3-alpine3.12

WORKDIR /code

COPY requirements.txt /code
RUN pip install -r requirements.txt

{%- for port in ports -%}
EXPOSE {{ port }}
{% endfor %}

COPY . /code

CMD ["gunicorn", "-b", "0.0.0.0:80", "-w", "4", "main:app"]
